//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.14 at 06:07:38 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://api.mobipalma.mobi/docs/")
package jaxbClases;
